name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate Keystore
        env:
          KEYSTORE_PASSWORD: Mani_3840494915_Mani
          KEY_PASSWORD: Mani_3840494915_Mani
          KEY_ALIAS: Mani_3840494915_Mani
        run: |
          keytool -genkeypair -v \
            -keystore release.jks \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -alias "$KEY_ALIAS" \
            -storepass "$KEYSTORE_PASSWORD" \
            -keypass "$KEY_PASSWORD" \
            -dname "CN=Airdrop Manager, OU=Dev, O=MyOrg, L=City, S=State, C=IR"

      - name: Convert to Base64
        run: |
          base64 release.jks > release.jks.base64

      - name: Upload Base64 to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: keystore-base64
          path: release.jks.base64
